name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Build NuGet package
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: dotnet pack -p:PackageVersion=1.0.0-alpha1 --configuration Release
    - name: Set NuGet creds
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./Set-NuGetCredentials -ConfigFile ./nuget.config -Source gpr-test -Username zivkan -Password $env:GITHUB_TOKEN
    - name: Publish NuGet package
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: dotnet nuget push UtilityDisposables/bin/Release/UtilityDisposables.1.0.0-alpha1.nupkg -s "https://nuget.pkg.github.com/nloum/index.json"
