name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103' # SDK Version to use.
    - run: dotnet build TreeLinq/TreeLinq.csproj
    - name: Make NuGet package
      run: dotnet pack TreeLinq/TreeLinq.csproj
    #- name: Make NuGet package
    #  run: dotnet push TreeLinq/TreeLinq.csproj -k "${{ secrets.GITHUB_TOKEN }}" -s "https://nuget.pkg.github.com/nloum/index.json"
